id = "midio"
name = "Midio"
description = "Midio language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Kristian Hasselknippe <kristian@midio.com>"]
repository = "https://github.com/midio/zed-midio"

[grammars.midio]
repository = "https://github.com/midio/tree-sitter-midio.git"
rev = "b63049bec13e1d0c7a16b2ae5431e92533befdcb"
